[layout]
start_container = ["app_launcher", "workspaces"]
center_container = ["date_time"]
end_container = ["battery"]

[notification]
anchor = "top-right"
auto_dismiss = true
ignored = []
timeout = 3000
max_count = 5

[battery]
full_battery_level = 100
hide_label_when_full = true
label = true
tooltip = true
