[[module_groups]]
widgets = [ "quick_settings", "battery" ]
spacing = 4
style_classes = [ "compact" ]

[layout]
start_container = ["app_launcher", "workspaces"]
center_container = ["date_time"]
# end_container = ["quick_settings", "battery", "system_tray"]
end_container = ["@group:0", "system_tray"]

[general]
layer = "top"
location = "top"
margin = "6px 6px 0px 6px" # Spacing that makes the bar float

[app_launcher]
icon_size = 16 # Bar button icon
app_icon_size = 48 # Size of app icons in launcher
show_descriptions = false

[keybinds]
enabled = true
path = "~/.config/hypr/hyprbinds.conf"

[workspaces]
count = 3
hide_unoccupied = false
ignored = [] # or []
reverse_scroll = true
empty_scroll = false
default_label_format = "{id}"
icon_map = {}

[notification]
enabled = true
anchor = "top-right"
auto_dismiss = true
ignored = []
timeout = 3000
max_count = 5

[battery]
full_battery_level = 100
hide_label_when_full = true
label = true
tooltip = true

[date_time]
clock_format = "24h"  # 24h or "12h"
format = "%b"

[system_tray]
icon_size = 16
ignored = [ ]

[quick_settings]
bar_icons = ["network","audio", "brightness"] # quick setting buttons to display on the bar
