[layout]
start_container = ["app_launcher", "workspaces"]
center_container = ["date_time"]
end_container = ["quick_settings", "battery", "system_tray"]

[workspaces]
count = 3
hide_unoccupied = true
ignored = [] # or []
reverse_scroll = true
empty_scroll = false
default_label_format = "{id}"
icon_map = {}

[notification]
anchor = "top-right"
auto_dismiss = true
ignored = []
timeout = 3000
max_count = 5

[battery]
full_battery_level = 100
hide_label_when_full = true
label = true
tooltip = true

[date_time]
clock_format = "24h"  # 24h or "12h"
format = "%b"

[system_tray]
icon_size = 16
ignored = [ ]
