[[module_groups]]
widgets = ["hyprpicker", "emoji_picker", "cliphist" ]
spacing = 4
style_classes = [ "compact" ]

[[module_groups]]
widgets = ["quick_settings", "battery" ]
spacing = 4
style_classes = [ "compact" ]

[layout]
start_container = ["app_launcher", "workspaces", "window_title"]
center_container = ["date_time", "power_profiles", "mpris"]
# end_container = ["quick_settings", "battery", "system_tray"]
end_container = ["system_tray", "@group:0","@group:1"]

[general]
layer = "top"
location = "top"

  [general.screen_corners]
  enabled = true
  size = 20

[app_launcher]
icon_size = 16 # Bar button icon
app_icon_size = 48 # Size of app icons in launcher
show_descriptions = true

[emoji_picker]
icon = ""
label = false
tooltip = true

[mpris]
icon_size = 16
transition_duration = 300
tooltip = true

[cliphist]
icon = ""
label = false
tooltip = true

[keybinds]
enabled = true
path = "~/.config/hypr/hyprbinds.conf"

[workspaces]
count = 3
hide_unoccupied = false
ignored = [] # or []
reverse_scroll = true
empty_scroll = false
default_label_format = "{id}"
icon_map = {}

[notification]
enabled = true
anchor = "top-right"
auto_dismiss = true
ignored = []
timeout = 3000
max_count = 5

[battery]
full_battery_level = 100
hide_label_when_full = true
label = true
tooltip = true

[date_time]
clock_format = "24h"  # 24h or "12h"
format = "%b %d"

[system_tray]
icon_size = 16
ignored = [ ]

[quick_settings]
bar_icons = ["network","audio", "bluetooth","brightness"] # quick setting buttons to display on the bar
show_network_name = true
show_audio_percent = false
show_brightness_percent = false

[hyprpicker]
icon_size = 16
tooltip = true

[power_profiles]
icon_size = 16

[theme]
name = "matugen"
